name: CD

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Compile
              run: echo Hello, world!

    DeployDev:
        name: Deploy to Dev
        if: github.event_name == 'pull_request'
        needs: [Build]
        runs-on: ubuntu-latest
        environment:
            name: Development
            url: 'http://localhost'
        steps:
            - name: Deploy
              run: docker compose up
    
    DeployStaging:
        name: Deploy to Staging
        if: github.event.ref == 'refs/heads/release'
        needs: [Build]
        runs-on: ubuntu-latest
        environment:
            name: Staging
            url: 'http://localhost'
        steps:
            - uses: actions/checkout@v2
            - name: Deploy
              run: docker compose up

    DeployProd:
        name: Deploy to Production
        if: github.event.ref == 'refs/heads/main'
        needs: [Build]
        runs-on: ubuntu-latest
        environment:
            name: Staging
            url: 'http://localhost'
        steps:
            - uses: actions/checkout@v2
            - name: Deploy
              run: docker compose up

        
        

